#!/usr/bin/env bash
# Script that transfers a file from our client to a server

if (($# < 3)); then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  file_path=$1
  ip=$2
  username=$3
  pk_path=$4
  scp -o StrictHostKeyChecking=no -i "$pk_path" "$file_path" "$username"@"$ip":~/
fi

