#!/usr/bin/env bash
# Script display some text based on while loop and if else statements

i=1

while ((i <= 10));
do
  if ((i == 4)); then
    echo "bad luck"
  elif ((i == 8)); then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done

