#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes

i=0
j=1

while ((i <= 12));
do
  echo "Hour: $i"
  j=1
  while ((j <= 59));
  do
    echo "$j"
    ((j++))
  done
  ((i++))
done

